language: rust
matrix:
  include:
    - os: linux
      rust: 1.23.0
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo +nightly generate-lockfile -Z minimal-versions;
    cargo build --verbose;
    cargo test --verbose;
    fi
branches:
  only:
    - master
