language: rust
matrix:
  include:
    - os: linux
      rust: 1.16.0
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: beta
    - os: osx
      rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
branches:
  only:
    - master
